# Project Name
TARGET = key_controlled_ocillators

# Sources
CPP_SOURCES = key_controlled_ocillators.cpp

# Library Locations
LIBDAISY_DIR = ../../../../../../../../../dev/daisy_seed/libDaisy/
DAISYSP_DIR = ../../../../../../../../../dev/daisy_seed/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
